### ISSUE TITLE
Github issues to work on?

### ISSUE THREAD

**Issue by orendon** [mrhead/ruby_arena#1]
Hi Patrik, just saw your post, sounds like fun!

I would like to help growing this from the very beginning, what about creating a roadmap or some github issues with specific task to work on? or any suggestion for newcomers?

**Comment by mrhead** [comment]
Hello Oscar,

I just wanted to make this project "public" this week.

To be honest I do not have experiences with managing open source project, but github issues sounds ok to me. I will put some milestones into the issues and update README.md with current status of the project and how to contribute.

And many thanks for your interest! Stay tuned and hopefully we can have first robot battle very soon ;)

**Comment by mrhead** [comment]
I've created some issues and also I've updated readme with description how to run battles and create your own robot (AI).

@orendon could you please check the issues and README.md and let me know what you think? Many thanks!

**Comment by orendon** [comment]
awesome, I think is a really good start.

Will take a look at the codebase to see wich tickets fits as a start, thanks
