### ISSUE TITLE
Ruby is crashing when `rspec spec/gui_spec.rb` is executed

### ISSUE THREAD

**Issue by mrhead** [mrhead/ruby_arena#29]
It looks like issue in Gosu: https://github.com/jlnr/gosu/issues/108

Maybe I will just remove tests for Gui until it is fixed.

**Comment by abinoam** [comment]
I was not able to reproduce it here on my machine (running ruby 2.0.0dev (2011-12-28 trunk 34149) [x86_64-darwin11.2.0]).

**Comment by abinoam** [comment]
Ooops... I think that's because of this commit (disabling the bug).
df3a62c7aa37836d39af4051454d6d45d6ee358e

**Comment by mrhead** [comment]
Fixed in https://github.com/mrhead/ruby_arena/pull/37

**Comment by mrhead** [comment]
@abinoam Many thanks!

**Comment by abinoam** [comment]
@mrhead you're welcome!
