### ISSUE TITLE
Add license to README.md

### ISSUE THREAD

**Issue by mrhead** [mrhead/ruby_arena#40]
I am thinking about releasing this code under the MIT license.

But to be honest I do not have any experiences with licensing, so if you have some other ideas then please post them here.

**Comment by orendon** [comment]
Apache and MIT license's are probably the "most permissive" ones

You can take a look at this site to help you go further http://choosealicense.com/

**Comment by mrhead** [comment]
Done. I've licensed it under MIT license.
